name: medilink
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.1.0
  hive: ^2.2.3
  uuid_v4: ^1.0.2
  equatable: ^2.0.7
  dartz: ^0.10.1
  shared_preferences: ^2.5.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: openSans Bold
      fonts:
        - asset: assets/fonts/openSans-Bold.ttf
    - family: openSans Italic
      fonts:
        - asset: assets/fonts/openSans-Italic.ttf
    - family: openSans Regular
      fonts:
        - asset: assets/fonts/openSans-Regular.ttf


    